{% set version = "2.5" %}
{% set sha256 = "1404b87e44c4452b2f329abb81ce4a8383ed5b7e94f38ff2815c5bed62ec2c7f" %}


package:
  name: souporcell
  version: {{version}}

source:
  url: https://github.com/wheaton5/souporcell/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  run_exports:
    - {{ pin_subpackage('souporcell', max_pin="x.x") }}

requirements:
  build:
    - python 
    - setuptools
    - rust
    - samtools
    - umi_tools
    - scikit-learn
    - bcftools
    - htslib
    - freebayes
    - minimap2
    - vartrix
    - tensorflow
    - pyvcf
    - pystan
    - pyfaidx

  run:
    - python
    - numpy
    - scipy
    - pandas
    - scikit-learn
    - samtools
    - bcftools
    - htslib
    - freebayes
    - minimap2
    - vartrix
    - tensorflow
    - pyvcf
    - pystan
    - pyfaidx

test:
  commands:
    - python -c "import souporcell"

about:
  home: https://github.com/wheaton5/souporcell
  license: MIT